Create Events Table
VolunteerOne/volunteer-one-app pull request #101
Opened 2023-03-08 19:02 UTC by edwardsung4217

#11 
> Team member: Edward
> Use Case ID:

Fixes #11

## Expected Behavior
To have events table created

## Issue
Create events table in the database

2023-03-11 05:37 UTC, dzeleniak commented
Everything looks great to me. 
As I said in the private message, the raw SQL would be overwritten by the migrations done in initialization.go, but we will probably need to remove the file entirely to fix that.

The only change that I'd like to see is getting rid of the blocks of code commented out, but after that, I'll approve.

2023-03-11 05:38 UTC, dzeleniak requested changes
- Remove Comments from loginController.go

2023-03-11 06:35 UTC, edwardsung4217 commented
> Everything looks great to me. As I said in the private message, the raw SQL would be overwritten by the migrations done in initialization.go, but we will probably need to remove the file entirely to fix that.
> 
> The only change that I'd like to see is getting rid of the blocks of code commented out, but after that, I'll approve.

I actually pushed the wrong commit. The commit about the login stuff was supposed to go to my fork and not this PR. I have uncommitted it.

2023-03-13 00:56 UTC, dzeleniak approved these changes

2023-03-13 00:56 UTC, merged