[FS0.0] | [Create New Password Screen]
VolunteerOne/volunteer-one-app pull request #110
Opened 2023-03-24 03:20 UTC by GoSec-Hub

# [FS0.0] | [Create New Password Screen]
> Team member: @GoSec-Hub 
> Use Case ID: [FS0.0]

Fixes #69 

## Expected Behavior
The "New Password" screen will take an account's current and new passwords. These will then be displayed on the console after clicking the bottom (to be addressed).

## Issue
Current issues are within the styling of the page. 
1. Need to fix the location of the input boxes and the text within.

### - Usage 
1. Input new password
2. Input current password
3. Click "RESET PASSWORD"

### - Evidence/Logs

![Screenshot 2023-03-23 at 8 11 38 PM](https://user-images.githubusercontent.com/61207730/227415044-74478703-a3e8-470f-bec0-88da5819cb7f.png)

2023-03-24 19:52 UTC, carmen-lee requested changes
Please fix styling. You can take a look at the other Onboarding pages as reference.

2023-03-24 19:52 UTC, carmen-lee commented on frontend/VolunteerOne/screens/Onboarding/NewPassword.js
> -                    />
You can probably copy this over and change some variables names to fix the styling

2023-03-29 04:05 UTC, carmen-lee commented on frontend/VolunteerOne/screens/Home/index.js
This file has been deleted and replaced by another screen so I think it might cause a merge conflict. Please remove this file for now 10q!

2023-03-29 04:09 UTC, carmen-lee approved these changes

2023-04-17 16:58 UTC, mattacy approved these changes
Looks good, the styling may need to be edited to better see the placeholder text in the input boxes.

Will merge now

2023-04-17 16:58 UTC, merged