Forgot pass
VolunteerOne/volunteer-one-app pull request #111
Opened 2023-03-24 03:54 UTC by GoSec-Hub

# [FS0.3] | [Create ForgotPassword Screen]
> Team member: @GoSec-Hub 
> Use Case ID: FS0.3

Fixes #68 

## Expected Behavior
The user shall input their new password and confirm it. For not, the code shall display these inputs on the console log.

## Issue

### - Usage 
1. User shall input their new password
2. User shall input a password confirmation
3. Take the user back to the main page

### - Considerations 
Extra cases to consider 
1. Usage of secure text for both input fields
2. The creation of a follow-up page before taking the user back to the login screen

### - Evidence/Logs

![Screenshot 2023-03-23 at 8 50 03 PM](https://user-images.githubusercontent.com/61207730/227420243-fe606ee8-b7f0-4493-8a48-fc4f58e88733.png)

2023-03-29 03:32 UTC, cerasamson approved these changes

2023-03-29 03:32 UTC, cerasamson commented on frontend/VolunteerOne/screens/Onboarding/ForgotPassword.js
> +                        RESET PASSOWRD
```suggestion
                        RESET PASSWORD
```

2023-03-29 03:33 UTC, cerasamson commented on frontend/VolunteerOne/screens/Onboarding/ForgotPassword.js
> +                        RESET PASSOWRD
Other than this typo, all looks good

2023-03-29 17:56 UTC, carmen-lee approved these changes

2023-03-29 18:04 UTC, carmen-lee requested changes
Please take a look at the figma file to replicate it as closely as possible. Please also remove the files as mentioned

2023-04-04 23:48 UTC, carmen-lee approved these changes

2023-04-04 23:48 UTC, merged