Send Email with Code
VolunteerOne/volunteer-one-app pull request #126
Opened 2023-03-28 06:50 UTC by edwardsung4217

#33 Send Email with Code
> Team member: Edward

Fixes #33 

## Expected Behavior
An endpoint that sends the user a code that allows them to reset their password has been added to the API

A new function called SaveResetCodeToUser adds the ability for the user to reset their password incase they forget it. The function will send the user an email with a code in which they will need as it is the verification.

### - Usage 
http://www.localhost:8000/login/email@example.com

### - Evidence/Logs
I can't currently provide evidence since my sendGrid account got suspended since I accidentally exposed the API key when I committed it.

2023-03-28 06:56 UTC, lazeroffmichael commented
I am thinking that we should move towards some type of `/api/v1/` scheme, however this route should be fine for now, thank you.

2023-03-28 06:56 UTC, lazeroffmichael approved these changes

2023-03-28 22:30 UTC, Rahgid requested changes

2023-03-28 22:30 UTC, Rahgid commented on backend/models/usersModel.go
While we're updating this file, can we remove the "id" field? This is included by gorm.Model already with the same properties.

2023-03-28 22:43 UTC, Rahgid commented on backend/models/usersModel.go
The field is exactly the same, it's just redundant since it's already included by gorm.Model. 

![image](https://user-images.githubusercontent.com/58805003/228383308-acd88151-0864-4d49-9b5f-a55a7ae45284.png)

2023-03-28 22:49 UTC, edwardsung4217 commented on backend/models/usersModel.go
Sounds good, ill delete it once im  available

2023-03-29 00:33 UTC, edwardsung4217 commented on backend/models/usersModel.go
It has been deleted, please approve now

2023-03-29 01:07 UTC, Rahgid approved these changes
Looks good for now, but please also update "EXAMPLEAPIKEY" with an environment variable once your account is reactivated.

2023-03-29 01:12 UTC, merged