created databases.sql
VolunteerOne/volunteer-one-app pull request #2
Opened 2023-02-23 22:10 UTC by yaaacii

created the .sql and added the `users` table

2023-02-24 01:41 UTC, Rahgid requested changes
I don't think "linestring" does what you think, it's meant for like a sequence of points (geometry stuff). Let's use a varchar for those fields.
You can specify a size like VARCHAR(255).

2023-02-24 02:42 UTC, yaaacii commented
Ah your right.

2023-02-24 11:06 UTC, Rahgid approved these changes

2023-02-24 11:13 UTC, Rahgid requested changes
Sorry, can we also add a "verified" field to help with Specs 1.2 and 1.3.4? We can worry about tokens to actually do verification in another table, but I think keeping a flag in the user table will be helpful for us.

2023-02-25 11:32 UTC, Rahgid approved these changes

2023-02-28 08:25 UTC, merged