Announcements
VolunteerOne/volunteer-one-app pull request #97
Opened 2023-03-08 00:52 UTC by Mtessier809

[Home Screen] Create Event Card 
[Home Screen] Create Announcement Card
 
Mathis Tessier 

Fixes #[Issue]
Creates event card and announcement card 
## Expected Behavior
Created Event Card inside of components that consists of a card header and card body. Depending on the data passed to the event card, it is generated differently. So far it can be used to generate event posts as well as announcements. 

Example Event Card 

![eventCard](https://user-images.githubusercontent.com/82081099/223590519-4473d43b-46e9-439e-86eb-9d29a1d483ba.PNG)

2023-03-08 01:07 UTC, cerasamson commented on frontend/VolunteerOne/navigation/Screens.js
> +        name="Announcments"
Fix typo :-)

2023-03-08 01:11 UTC, cerasamson commented on frontend/VolunteerOne/screens/Home/index.js
> +const dataList = [
I'm not sure if we want to have the dataList in the home page itself or in ```/constants``` (as ```events.js```) for readability purposes, but we can discuss

2023-03-08 01:12 UTC, cerasamson commented on frontend/VolunteerOne/screens/Home/index.js
> +    type: "announcment",
```suggestion
    type: "announcement",
```

2023-03-08 01:13 UTC, cerasamson commented on frontend/VolunteerOne/components/EventCard/CardBody.js
> +  } else if (type == "announcment") {
```suggestion
  } else if (type == "announcement") {
```

2023-03-08 01:20 UTC, cerasamson commented
As we discussed in the meeting earlier, we can probably combine styling from #88 and #89 to ```CardBody.js``` and ```CardHeader.js```.

2023-03-08 02:37 UTC, carmen-lee requested changes
Thanks for doing the dynamic dates! Looks great 👍 

- Fix typos (announcment -> announcement)
- create file in the folder 'constants' and put the mock data there

2023-03-21 23:22 UTC, cerasamson commented
Will be combined with another PR - #97

2023-03-23 02:27 UTC, closed without merging